approve-message: "The idea successfully approved"
decline-message: "The idea successfully declined"

cooldown: 10
cooldown-message: "You cant do this %remaining_time%"
no-permission-message: "You don't have permission to do that"

idea-is-empty-message: "Please fill your idea in command args"
too-long-idea: "your idea is too long, max characters length is 120"

command-if-approved: "give %player_name% diamond_helmet 1"

idea-item:
  material: "PAPER"
  head-base64: "omit this if you use simple material or you want player author"
  displayname: "&aIdea №%id%"
  lore:
    - "&c&lAuthor: %player%"
    - "&fIdea: %idea%"
    - "&aStatus: %status%"


pending-ideas-menu:
  title: "Pending ideas"
only-declined-menu:
  title: "Declined ideas"
only-approve-menu:
  title: "Approved ideas"
approval-menu:
  title: "Approval menu"


database-type: sqlite

mysql:
  host: 127.0.0.1
  port: 3306
  database: test_db
  username: elpomoika
  password: 1234