approve-message: "The idea successfuly approved"
decline-message: "The idea successfuly declined"

cooldown: 10
cooldown-message: "You cant do this %remaining_time%"
no-permission-message: "You don't have permission to do that"

idea-is-empty-message: "Please fill your ebanyi idea in command args"

command-if-approved: "give %player_name% diamond_helmet"

mysql:
  host: 127.0.0.1
  port: 3306
  database: test_db
  username: elpomoika
  password: 1234