name: EIdea
version: '1.0'
main: me.elpomoika.eidea.EIdea
api-version: '1.16'

permissions:
  eidea.default:
    description: Allow access for default players
  eidea.premium:
    description: Allow for premium players
  eidea.admin:
    description: Admin and moderators permission


commands:
  idea:
    usage: /idea <your idea>
  ideas: {}
  eidea:
    permission: "eidea.admin"
